name: Automated Website Testing & Report Deployment

on:
  push:
    branches: [main]
  workflow_dispatch:  # Allows manual trigger

jobs:
  test_website:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: true  # Ensure GitHub Actions can push changes

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          pip install selenium beautifulsoup4 requests openai webdriver-manager
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable xvfb chromium-chromedriver
          google-chrome --version
          
          if [ ! -f "/usr/bin/chromedriver" ]; then
            ln -s /usr/lib/chromium-browser/chromedriver /usr/bin/chromedriver
          fi

      - name: Ensure results directory exists
        run: mkdir -p results/screenshots

      - name: Run crawler to discover endpoints
        run: python scripts/crawler.py

      - name: Commit & Push Discovered Endpoints to Repository
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add results/endpoints.json
          git commit -m "Update discovered endpoints [GitHub Actions]"
          git push
        continue-on-error: true  # Prevent failure if there are no new changes

      - name: Capture screenshots using Selenium
        run: python scripts/screenshot.py

      - name: Generate AI-driven test cases
        run: python scripts/generate_tests.py

      - name: Generate test report
        run: python scripts/generate_report.py

      - name: Upload Screenshots & Report as Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: results/
